name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master              # publish whenever “master” is updated

      # Pages‑specific permissions must be available to the deploy job
    permissions:
      contents: read
    pages: write
    id-token: write          # needed for OIDC‑based deployment

    jobs:
      build_site:
        runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4       # ↗ current major :contentReference[oaicite:0]{index=0}

        # Uncomment if you prefer pnpm
        # - name: Install pnpm
        #   uses: pnpm/action-setup@v2
        #   with:
        #     version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4      # ↗ current major :contentReference[oaicite:1]{index=1}
        with:
          node-version: 18              # keep LTS, change if you need 20+
          cache: npm

          # Optional but recommended: enables Pages metadata and future‑proofs build
      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v5    # :contentReference[oaicite:2]{index=2}

      - name: Install dependencies
        run: npm ci

      - name: Build static site
        env:
          BASE_PATH: "/${{ github.event.repository.name }}"
        run: npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3   # ↗ required new major :contentReference[oaicite:3]{index=3}
        with:
          path: build/

        deploy:
          needs: build_site
        runs-on: ubuntu-latest
        environment:
          name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

        steps:
          - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4            # ↗ required new major :contentReference[oaicite:4]{index=4}
